#!/usr/bin/env python3
import argparse
import os
import re
import time
from pathlib import Path

import rclpy
from geometry_msgs.msg import PoseWithCovarianceStamped


def read_frame_id(text):
    match = re.search(r'^\s*frame_id:\s*(\S+)\s*$', text, re.MULTILINE)
    if not match:
        return 'map'
    return match.group(1)


def parse_pose_file_strict(path):
    text = Path(path).read_text()
    sections = {}
    current = None
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        if not line.startswith(' ') and line.endswith(':'):
            current = line[:-1].strip()
            sections[current] = {}
            continue
        if current and line.startswith('  ') and ':' in line:
            key, value = line.strip().split(':', 1)
            sections[current][key.strip()] = float(value.strip())

    frame_id = read_frame_id(text)
    position = sections.get('position', {})
    orientation = sections.get('orientation', {})
    covariance = sections.get('covariance', {})
    required = [
        ('position.x', position, 'x'),
        ('position.y', position, 'y'),
        ('orientation.z', orientation, 'z'),
        ('orientation.w', orientation, 'w'),
    ]
    for name, section, key in required:
        if key not in section:
            raise ValueError(f'missing {name} in {path}')

    return {
        'frame_id': frame_id,
        'position': {
            'x': position['x'],
            'y': position['y'],
            'z': position.get('z', 0.0),
        },
        'orientation': {
            'x': orientation.get('x', 0.0),
            'y': orientation.get('y', 0.0),
            'z': orientation['z'],
            'w': orientation['w'],
        },
        'covariance': {
            'x': covariance.get('x', 0.25),
            'y': covariance.get('y', 0.25),
            'yaw': covariance.get('yaw', 0.0685),
        },
    }


def build_msg(node, pose):
    msg = PoseWithCovarianceStamped()
    msg.header.stamp = node.get_clock().now().to_msg()
    msg.header.frame_id = pose['frame_id']
    msg.pose.pose.position.x = pose['position']['x']
    msg.pose.pose.position.y = pose['position']['y']
    msg.pose.pose.position.z = pose['position']['z']
    msg.pose.pose.orientation.x = pose['orientation']['x']
    msg.pose.pose.orientation.y = pose['orientation']['y']
    msg.pose.pose.orientation.z = pose['orientation']['z']
    msg.pose.pose.orientation.w = pose['orientation']['w']
    msg.pose.covariance[0] = pose['covariance']['x']
    msg.pose.covariance[7] = pose['covariance']['y']
    msg.pose.covariance[35] = pose['covariance']['yaw']
    return msg


def parse_args():
    parser = argparse.ArgumentParser(description='Publish a saved Go2 AMCL initial pose.')
    parser.add_argument(
        '--pose-file',
        default=os.path.join(os.path.expanduser('~'), 'go2_maps', 'go2_initial_pose.yaml'),
        help='saved pose YAML generated by save_map_and_pose.py',
    )
    parser.add_argument('--topic', default='/initialpose')
    parser.add_argument('--repeat', type=int, default=5)
    parser.add_argument('--period', type=float, default=0.5)
    args, _ros_args = parser.parse_known_args()
    return args


def main():
    args = parse_args()
    pose = parse_pose_file_strict(os.path.expanduser(args.pose_file))

    rclpy.init()
    node = rclpy.create_node('go2_publish_initial_pose')
    publisher = node.create_publisher(PoseWithCovarianceStamped, args.topic, 10)

    try:
        for i in range(max(1, args.repeat)):
            msg = build_msg(node, pose)
            publisher.publish(msg)
            rclpy.spin_once(node, timeout_sec=0.05)
            print(
                f'published initial pose {i + 1}/{max(1, args.repeat)}: '
                f'x={pose["position"]["x"]:.6f}, y={pose["position"]["y"]:.6f}, '
                f'z={pose["orientation"]["z"]:.6f}, w={pose["orientation"]["w"]:.6f}'
            )
            if i + 1 < max(1, args.repeat):
                time.sleep(args.period)
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
